Task_manager/Task/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordResetForm, MyPasswordSetForm, MyChangePasswordForm
from .views import TaskListView, TaskCreateView, TaskDetailView, TaskUpdateView, TaskDeleteView

urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing-page'),
    path('registration/', views.RegistrationView.as_view(), name='registration'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm),
         name='login'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset.html', form_class=MyPasswordResetForm),
         name='password_reset'),
    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name="password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_confirm.html",
                                                     form_class=MyPasswordSetForm), name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),

    path('passwordchange/',
         auth_views.PasswordChangeView.as_view(template_name='changepassword.html', form_class=MyChangePasswordForm,
                                               success_url='/passwordchangedone/'), name='passwordchange'),
    path('passwordchangedone/', auth_views.PasswordChangeView.as_view(template_name='passwordchangedone.html'),
         name='passwordchangedone'),

    path('tasks/', TaskListView.as_view(), name='task-list'),
    path('tasks/create/', TaskCreateView.as_view(), name='task-create'),
    path('tasks/<int:task_id>/', TaskDetailView.as_view(), name='task-detail'),
    path('tasks/<int:task_id>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('tasks/<int:task_id>/delete/', TaskDeleteView.as_view(), name='task-delete'),

    path('search/', views.SearchItemView.as_view(), name='search'),
]

Task_manager/Task_manager/urls.py
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


schema_view = get_schema_view(
    openapi.Info(
        title="Task Manager API",
        default_version='v1',
        description="API System",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Task.urls')),
    path('api/', include('Task_API.urls')),
    path('swagger<str:format>', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Task_manager/Task/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    PRIORITY_CHOICES = (
        ('Low', 'Low'),
        ('Medium', 'Medium'),
        ('High', 'High'),
    )

    title = models.CharField(max_length=255)
    description = models.TextField()
    due_date = models.DateTimeField()
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    is_complete = models.BooleanField(default=False)
    creation_datetime = models.DateTimeField(auto_now_add=True)
    last_update_datetime = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='task_photos/', null=True, default=None)

    def __str__(self):
        return self.title

Task_manager/Task/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordResetForm, \
    SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Task


class RegistrationsFrom(UserCreationForm):
    username = forms.CharField(label='Enter Username', min_length=3, max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Enter email', required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Enter Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = UsernameField(label='Enter Username',
                             widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': True}))
    password = forms.CharField(label='Enter Password', strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'autocomplete': 'current-password'}))


class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label='Enter Email', max_length=254,
                             widget=forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'email'}))


class MyPasswordSetForm(SetPasswordForm):
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
                                    help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'autocomplete': 'new-password'}))


class MyChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old Password', strip=False, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'autocomplete': 'current-password', 'autofocus': True}))
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
                                    help_text=password_validation.password_validators_help_text_html())
    new_password2 = forms.CharField(label='New Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'autocomplete': 'new-password'}))


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date', 'priority', 'is_complete', 'photo']

Task_manager/Task/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from .forms import RegistrationsFrom, TaskForm
from django.contrib import messages
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin


class LandingPageView(View):
    template_name = 'home.html'

    def get(self, request):
        return render(request, self.template_name)


class RegistrationView(View):
    def get(self, request):
        form = RegistrationsFrom()
        context = {
            'form': form
        }
        return render(request, 'registration.html', context)

    def post(self, request):
        form = RegistrationsFrom(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Congratulations!! Registration Successfully!')
        context = {
            'form': form
        }
        return render(request, 'registration.html', context)


class TaskListView(LoginRequiredMixin, View):
    def get(self, request):
        tasks = Task.objects.all().order_by('priority')
        context = {
            'tasks': tasks,
        }
        return render(request, 'task_list.html', context)


class TaskCreateView(LoginRequiredMixin, View):
    def get(self, request):
        form = TaskForm()
        return render(request, 'task_creation.html', {'form': form})

    def post(self, request):
        form = TaskForm(request.POST, request.FILES)
        if form.is_valid():
            task = form.save(commit=False)
            task.creator = request.user
            task.save()
            messages.add_message(request, messages.SUCCESS, 'Congratulations! Task created successfully.')
            return redirect(reverse('task-list'))
        else:
            messages.error(request, 'Error submitting the form. Please check your inputs.')
            print(form.errors)  # Print form errors for debugging purposes
            print(request.POST)
        return render(request, 'task_creation.html', {'form': form})




class TaskDetailView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)
        task = Task.objects.get(pk=task_id)
        return render(request, 'task_details.html', {'task': task})


class TaskUpdateView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)
        form = TaskForm(instance=task)
        return render(request, 'task_update.html', {'form': form, 'task': task})

    def post(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)
        form = TaskForm(request.POST, request.FILES, instance=task)
        if form.is_valid():
            if 'new_photo' in request.FILES:
                new_photo = request.FILES['new_photo']
                task.photo = new_photo
            form.save()
            return redirect(reverse('task-list'))
        return render(request, 'task_update.html', {'form': form, 'task': task})


class TaskDeleteView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        task = get_object_or_404(Task, pk=task_id)
        return render(request, 'task_delete_confirm.html', {'task': task})

    def post(self, request, task_id):
        task = Task.objects.get(pk=task_id)
        task.delete()
        return redirect(reverse('task-list'))


class SearchItemView(View):
    template_name = 'search.html'

    def get(self, request):
        query = request.GET.get('query')
        if query:
            task = Task.objects.filter(Q(title__icontains=query))
            return render(request, self.template_name, {'task': task})
        else:
            return render(request, self.template_name, {'message': 'Sorry!! No Match!'})

Task_manager/Task/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Task Manager</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="static/css/main.css">
    <title>Task Manager | {% block title %} {% endblock title %}</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="">Task Manager</a>
        </nav>
    </div>

        {% block main-content %} {% endblock main-content%}


    <!-- Include Bootstrap JS (at the end of the body) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Task_manager/Task/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container my-5">
        <div class="col-sm-6 offset-sm-3">
         <h3>Change Password</h3>
             <hr>
           <form action="" method="POST" novalidate class="shadow p-5">
             {% csrf_token %}
               {% for fm in form %}
                    <div class="form-group mb-3">
                        {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors | striptags}}</small>
                    </div>
               {% endfor %}
             <button type="submit" class="btn btn-primary">Submit</button>
               {% if form.non_field_errors %}
                {% for error in form.non_field_error %}
                <p class="alert alert-danger my-3">{{error}}</p>
                {% endfor %}
               {% endif %}
           </form>
    </div>
</div>
 <!-- Add Bootstrap JS and jQuery scripts (for Bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

Task_manager/Task/templates/create_photo_task.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Task List {% endblock title %}

{% block main-content %}
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title">Upload Photos for Task</h1>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="task_title" class="form-label">Select Task Title:</label>
                                <select id="task_title" name="task_title" class="form-select">
                                    {% for task in tasks %}
                                        <option value="{{ task.id }}">{{ task.title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="photo" class="form-label">Upload Photo:</label>
                                <input type="file" id="photo" name="photo" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary">Upload Photo</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main-content %}

Task_manager/Task/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
      /* Add hover effect for buttons */
      .btn-primary:hover {
        background-color: #007bff;
      }

      /* Add hover effect for links */
      .btn-primary:hover a {
        text-decoration: none; /* Remove underline on hover */
      }
    </style>

</head>

<body>

  <div class="content">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-12">
              <div class="form-block">
                  <div class="mb-4 mt-4">
                      <h1>Welcome To Task Manager</h1>
                  </div>
                  <label>Log in if you already have registered!</label>
                  <div class="form-group last mb-4">
                      <div>
                          <a style="text-decoration: none; color: white;" href="{% url 'login' %}"><button class="btn btn-pill text-white btn-block btn-success">
                            Login
                          </button></a>
                      </div>
                  </div>
                  <label>If not register.Register here!</label>
                  <div class="form-group last mb-4">
                      <div>
                          <a style="text-decoration: none; color: white;" href="{% url 'registration' %}"> <button class="btn btn-pill text-white btn-block btn-primary">
                            Register
                          </button></a>
                      </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

Task_manager/Task/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login Form {% endblock title %}
{% block main-content %}
    <div class="container">
         <div class="row my-3">
          <div class="col-sm-6 offset-sm-3">
           <h3>Login</h3>
           <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                  <div class="form-group mb-3">
                    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors | striptags}}</small>
                   </div>
                {% endfor %}
                   <br>
                <small><a href="{% url 'password_reset' %}">Forgot Password ?</a></small> <br>
                <input type="submit" class="btn btn-primary mt-4" value="Login">
                <br>
                <div class="text-center text-primary fw-bold"><small>New to Task Manager ? <a href="{% url 'registration' %}"
                   class="text-danger">Create an Account</a></small></div>
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{error}}</p>
                        {% endfor %}
                    {% endif %}
               </form>
          </div>
          </div>
        </div>
{% endblock main-content %}

Task_manager/Task/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row my-3">
          <div class="col-sm-6 offset-sm-3">
           <h3>Reset Password</h3>
           <hr>
       <form action="" method="POST" novalidate class="shadow p-5">
        {% csrf_token %}
         {% for fm in form %}
          <div class="form-group mb-3">
            {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors | striptags}}</small>
          </div>
         {% endfor %}
        <div class="text-end">
         <button type="submit" class="btn btn-success">Submit</button>
        </div>
        <br>
        <div class="text-center text-primary fw-bold"><small>Existing User ? <a href="{% url 'login' %}"
           class="text-danger">Login Now</a> </small></div>
   </form>
  </div>
 </div>
</div>
 <!-- Add Bootstrap JS and jQuery scripts (for Bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

Task_manager/Task/templates/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container my-5">
     <div class="row">
      <div class="col-sm-6 offset-sm-3 text-center">
          <h3>Password Reset Complete!!</h3>

          <div style="width:80%;height:0;padding-bottom:50%;position:relative;">
              <iframe src="https://giphy.com/embed/YlSR3n9yZrxfgVzagm" width="200" height="200" style="position:absolute" frameBorder="0" class="giphy-embed" ></iframe>
          </div>
      </div>
     </div>
    </div>
 <!-- Add Bootstrap JS and jQuery scripts (for Bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

Task_manager/Task/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3 class="alert-heading text-center">Well Done</h3>
   <p>An Email has been sent with instructions to reset your password. <b>Check your Email</b> </p>
  </div>
 </div>
</div>
 <!-- Add Bootstrap JS and jQuery scripts (for Bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

Task_manager/Task/templates/passwordchangedone.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <!-- Add Bootstrap CSS link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container my-5">
     <div class="row">
      <div class="col-sm-9 offset-sm-1 text-center">
          <h3>Password Changed Successfully!!</h3>
          <div style="width:80%;height:0;padding-bottom:50%;position:relative;">
              <iframe src="https://giphy.com/embed/YlSR3n9yZrxfgVzagm" width="200" height="200" style="position:absolute" frameBorder="0" class="giphy-embed" ></iframe>
          </div>
      </div>
     </div>
    </div>
 <!-- Add Bootstrap JS and jQuery scripts (for Bootstrap) -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

Task_manager/Task/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Registration Form {% endblock title %}

{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>User Registration</h3>
   <hr>

   <form action="" method="POST" novalidate class="shadow p-5">
    {% for message in messages %}
     <p class=" text-center text-success mb-5">{{message}}</p>
    {% endfor %}

    {% csrf_token %}
     {% for fm in form %}
      <div class="form-group mb-3">
        {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors | striptags}}</small>
      </div>
     {% endfor %}
    <div class="text-end">
     <button type="submit" class="btn btn-success">Submit</button>
    </div>
    <br>
    <div class="text-center text-primary fw-bold"><small>Existing User ? <a href="{% url 'login' %}"
       class="text-danger">Login Now</a> </small></div>
   </form>
  </div>
 </div>
</div>
{% endblock main-content %}

Task_manager/Task/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Product Detail{% endblock title %}
{% block main-content %}
<div class="container my-5">
    <h2 class="">Search Result...</h2>
    <hr>
    <br>
    <h3 class="text-center text-warning">{{message}}</h3>
    {% for t in task %}
    <div class="row">
          <div class="col-sm-6 text-center align-self-center">
           <img height="250" width="250" src="{{t.photo.url}}" alt="Task Image Not Found" class="img-fluid img-thumbnail">
          </div>
          <div class="col-sm-5 offset-sm-1">
           <h2> Title: {{t.title}}</h2>
           <hr>
           <p> Description: {{t.description}}</p> <br>
            <h3>{{t.due_date}}</h3>
            <h3>{{t.priority}}</h3>
            <h3>{{t.is_complete}}</h3>
            <h3></h3>
          </div>
         </div>
    <hr>
    <br>
    {% endfor %}
</div>
{% endblock main-content %}

Task_manager/Task/templates/task_delete_confirm.html
{% extends 'base.html' %}

{% block title %}Confirm Task Deletion{% endblock title %}

{% block main-content %}
<div class="container text-center">
    <h1>Confirm Task Deletion</h1>
    <p>Are you sure you want to delete the task <strong class=" text-warning"> {{ task.title }}?</strong></p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirm Delete</button>
        <a href="{% url 'task-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock main-content %}

Task_manager/Task/templates/task_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Task List {% endblock title %}
{% block main-content %}

<div class="container">
  <h1 class="text-center">Task List</h1>
    {% for message in messages %}
     {% if message.tags == 'success' %}
            <p class="text-center text-success mb-5">{{ message }}</p>
        {% endif %}
    {% endfor %}
  <div style="text-align:right; padding-bottom:4px">
      <a href="{% url 'task-create' %}"><button class="btn btn-success">Create New Task</button></a>
    </div>
      <form class="d-flex" method="get" action="{% url 'search' %}">
           <input class="form-control me-2" name="query" type="text" placeholder="Search" aria-label="Search">
           <button class="btn btn-warning" type="submit">Search</button>
      </form>
  <table class="table">
    <thead>
      <tr>
        <th>Number</th>
        <th>Title</th>
        <th>Description</th>
        <th>DueDate</th>
        <th>CreateTime</th>
        <th>UpdateTime</th>
        <th>Priority</th>
        <th>Complete</th>
        <th>Photo</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
            {% for task in tasks %}
      <tr>
          <td>{{forloop.counter}}</td>
          <td>{{ task.title }}</td>
          <td>{{ task.description }}</td>
          <td>{{ task.due_date }}</td>
          <td>{{ task.creation_datetime }}</td>
          <td>{{ task.last_update_datetime }}</td>
          <td>{{ task.get_priority_display }}</td>
          <td>
              {% if task.is_complete %}
              <span class="badge badge-success">Complete</span>
              {% else %}
              <span class="badge badge-warning">Incomplete</span>
              {% endif %}
          </td>
          <td>
              {% if task.photo %}
              <img src="{{ task.photo.url }}" alt="Task Photo" width="100" height="50">
              {% else %}
              <p>No image found</p>
              {% endif %}
          </td>
          <td>
              <div style="display: flex;">
                  <a href="{% url 'task-detail' task.id %}" class="btn btn-primary btn-sm">Details</a>
                  <a href="{% url 'task-update' task.id %}" class="btn btn-warning btn-sm">Update</a>
                  <a href="{% url 'task-delete' task.id %}" class="btn btn-danger btn-sm">Delete</a>
              </div>
          </td>
      </tr>
      {% endfor %}

    </tbody>

  </table>
</div>
{% endblock main-content %}